-- ====================================================================
-- stfd_features：STFD v2.1 九大模組臨床特徵字典（86項Feature）
-- 適用資料庫：sleep_tcm_db（或你自己命名的資料庫）
-- 使用方式：在 Supabase Dashboard → SQL Editor → 貼上全部內容 → Run
-- ====================================================================

CREATE TABLE stfd_features (
  feature_id VARCHAR(10) PRIMARY KEY,
  module_code VARCHAR(2) NOT NULL,
  priority VARCHAR(20) NOT NULL,
  feature_type VARCHAR(60) NULL,
  name_en VARCHAR(150) NULL,
  name_zh_tw VARCHAR(60) NOT NULL,
  clinical_definition VARCHAR(300) NULL,
  clinical_boundary VARCHAR(300) NULL,
  patient_question_zh_tw VARCHAR(300) NOT NULL,
  response_type VARCHAR(200) NULL,
  time_window VARCHAR(30) NULL,
  related_features VARCHAR(100) NULL,
  sleep_relevance VARCHAR(150) NULL,
  tcm_knowledge_link VARCHAR(300) NULL,
  evidence_status VARCHAR(30) NOT NULL DEFAULT 'Draft',
  version_added VARCHAR(10) NOT NULL DEFAULT '2.1',
  status VARCHAR(20) NOT NULL DEFAULT 'active'
);


-- ---------------- Module A ----------------
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('S01', 'A', 'Core', 'Sleep symptom', 'Difficulty initiating sleep', '入睡困難', '有充分睡眠機會時，主觀覺得難以開始睡眠。', '與單純「自述睡得晚」區分；若因主動延後上床，應另記 L05/L08。', '最近兩週，您上床準備睡覺後，是否常覺得難以入睡？', '4-point frequency: 0 Never / 1 Occasionally / 2 Often / 3 Almost always; optional sleep-latency minutes', 'Past 2 weeks', 'M01, M02, L05, L08', 'INS-ONSET; COMISA', '不寐之入睡困難表現；心神、情志與陰陽失調相關知識節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('S02', 'A', 'Core', 'Sleep symptom', 'Frequent nocturnal awakenings', '夜間易醒', '主要睡眠時段內反覆醒來，造成睡眠連續性下降。', '與 S03「醒後難再入睡」分開；本項只記醒來是否頻繁。', '最近兩週，您是否常在夜間睡眠中醒來多次？', 'Numeric count + optional frequency rating', 'Past 2 weeks', 'S03, K01, S10, S11', 'INS-MAINT; OSA; COMISA', '不寐之易醒；可連結心神不寧、痰熱、陰血不足等知識，但不直接輸出證型');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('S03', 'A', 'Core', 'Sleep symptom', 'Difficulty returning to sleep', '醒後難再入睡', '夜間醒來後，需要較長時間才能再次入睡。', '與 S02 分開；可僅醒一次但長時間無法再睡。', '最近兩週，夜間醒來後，您是否常需要很久才能再睡著？', '4-point frequency: 0 Never / 1 Occasionally / 2 Often / 3 Almost always; optional minutes awake', 'Past 2 weeks', 'S02, M01, M02', 'INS-MAINT; COMISA', '不寐之醒後難寐；心神、情志與陰陽失調相關節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('S04', 'A', 'Core', 'Sleep symptom', 'Early morning awakening', '過早醒來', '比預期或需要的起床時間提早醒來，且難以再睡。', '不可只以時鐘時間定義；須相對於個人預定起床時間與睡眠需求。', '最近兩週，您是否常比預定起床時間提早醒來，且無法再睡？', '4-point frequency: 0 Never / 1 Occasionally / 2 Often / 3 Almost always; optional minutes early', 'Past 2 weeks', 'S03, M05', 'INS-EARLY', '不寐之早醒；可連結情志與陰血相關知識節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('S05', 'A', 'Core', 'Sleep quantity', 'Short sleep duration', '睡眠時間不足', '實際總睡眠時間低於個人需求，並可能伴隨日間影響。', '與「在床時間短」及主動熬夜區分；可與 L08、L11 共同解讀。', '最近兩週，您平均每晚實際睡眠大約幾小時？', 'Numeric hours and minutes', 'Past 2 weeks', 'S12, S14, L08, L11', 'INSOMNIA; SLEEP-DEPRIVATION', '睡眠失養與陰陽失調之描述性節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('S06', 'A', 'Core', 'Sleep quality', 'Non-restorative sleep', '睡醒後未恢復精神', '睡眠時間看似足夠，但醒後仍感到未休息或未恢復。', '與 S14 日間疲倦及 B01 全身無力區分；本項聚焦「睡醒當下的恢復感」。', '最近兩週，您是否常在睡醒後仍覺得沒有休息夠、精神未恢復？', '4-point frequency: 0 Never / 1 Occasionally / 2 Often / 3 Almost always', 'Past 2 weeks', 'S14, B01, S09', 'INSOMNIA; OSA; COMISA', '寐而不酣、寐後不解乏之描述性節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('S07', 'A', 'Extended', 'Sleep symptom', 'Dream-disturbed sleep', '多夢而影響睡眠', '主觀感覺夢境頻繁、鮮明或使睡眠品質下降。', '不是單純「記得做夢」；需有困擾、醒來或影響恢復感。', '最近兩週，您是否常因夢多或夢境鮮明而覺得睡眠受到影響？', '4-point frequency: 0 Never / 1 Occasionally / 2 Often / 3 Almost always', 'Past 2 weeks', 'S08, S06, M09', 'INS-MAINT; STRESS', '多夢、夢擾心神相關知識節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('S08', 'A', 'Extended', 'Sleep symptom', 'Nightmares', '惡夢', '造成恐懼、驚醒或顯著不適的負向夢境。', '與 S07 一般多夢區分；需有明顯負向情緒或驚醒。', '最近兩週，您是否曾因惡夢而驚醒或感到明顯害怕？', '4-point frequency: 0 Never / 1 Occasionally / 2 Often / 3 Almost always', 'Past 2 weeks', 'S07, M06, M09', 'PARASOMNIA; STRESS', '夢魘、神不守舍相關知識節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('S09', 'A', 'Core', 'Sleep-breathing symptom', 'Snoring', '打鼾', '睡眠中出現可被本人或他人察覺的鼾聲。', '鼾聲不等同 OSA；需與 S10、S11 及 STOP-Bang 等資料共同判斷。', '您或同住者是否發現您睡覺時經常打鼾？', '4-point frequency: 0 Never / 1 Occasionally / 2 Often / 3 Almost always', 'Past 1 month', 'S10, S11, F01', 'OSA; COMISA', '鼾眠、痰濕與氣道不利相關知識節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('S10', 'A', 'Core', 'Sleep-breathing symptom', 'Witnessed apneas', '目擊呼吸暫停', '睡眠時由他人觀察到呼吸停止、明顯停頓或不規則。', '與單純打鼾區分；屬高重要性篩檢訊號，但不是確診。', '是否有人看過您睡覺時出現呼吸停止或明顯停頓？', 'Yes / No / Unknown', 'Past 1 month', 'S09, S11, S12', 'OSA; COMISA', '鼾眠、氣機不利相關知識節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('S11', 'A', 'Core', 'Sleep-breathing symptom', 'Nocturnal choking or gasping', '夜間喘醒或嗆醒', '睡眠中因喘不過氣、嗆到或突然大口吸氣而醒來。', '與一般夜醒區分；若伴胸痛或急性呼吸困難需另行醫療評估。', '最近一個月，您是否曾在睡眠中因喘不過氣、嗆到或大口吸氣而醒來？', '4-point frequency: 0 Never / 1 Occasionally / 2 Often / 3 Almost always', 'Past 1 month', 'S09, S10, B08', 'OSA; COMISA', '肺氣不利、痰阻與鼾眠相關知識節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('S12', 'A', 'Core', 'Daytime consequence', 'Daytime sleepiness', '日間嗜睡', '白天存在強烈睡意或容易睡著的傾向。', '與 S14 疲倦區分：嗜睡是「想睡或會睡著」，疲倦是「缺乏體力或精神」。', '最近兩週，您白天是否常感到很想睡？', '4-point frequency: 0 Never / 1 Occasionally / 2 Often / 3 Almost always', 'Past 2 weeks', 'S13, S05, S09, S10', 'DAYTIME; OSA; INSUFFICIENT-SLEEP', '嗜睡、困倦相關描述性節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('S13', 'A', 'Core', 'Daytime consequence', 'Unintentional dozing', '非預期打瞌睡', '在沒有計畫睡覺的情況下，不由自主地打瞌睡或短暫入睡。', '比 S12 更具行為表現；需注意駕駛或工作安全。', '最近兩週，您是否曾在不打算睡覺時不小心打瞌睡或睡著？', '4-point frequency: 0 Never / 1 Occasionally / 2 Often / 3 Almost always', 'Past 2 weeks', 'S12, L06', 'DAYTIME; SAFETY; OSA', '困倦欲寐之行為表現節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('S14', 'A', 'Core', 'Daytime consequence', 'Daytime fatigue', '日間疲倦', '白天感到精神或體力不足，但不一定會睡著。', '與 S12 嗜睡及 B01 全身無力區分；本項聚焦白天功能與精力下降。', '最近兩週，您白天是否常覺得疲倦、沒有精神，但不一定想睡？', '4-point frequency: 0 Never / 1 Occasionally / 2 Often / 3 Almost always', 'Past 2 weeks', 'S06, S12, B01', 'DAYTIME; INSOMNIA; COMISA', '倦怠、少氣乏力之描述性節點');

-- ---------------- Module B ----------------
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('M01', 'B', 'Core', 'Cognitive-emotional symptom', 'Excessive worry', '過度擔心', '難以控制、反覆出現的擔心，可能妨礙放鬆或入睡。', '與 M02 思緒繁多區分；擔心通常有負向內容或未來導向。', '最近兩週，您是否常因反覆擔心事情而難以放鬆或入睡？', '4-point frequency: 0 Never / 1 Occasionally / 2 Often / 3 Almost always', 'Past 2 weeks', 'M02, M03, S01', 'INS-ONSET; STRESS', '思慮過度、心神不寧相關節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('M02', 'B', 'Core', 'Cognitive symptom', 'Racing thoughts', '思緒停不下來', '躺下或休息時思緒快速、連續或難以停止。', '不一定帶有擔心內容；與 M01 過度擔心分開。', '最近兩週，您躺下準備睡覺時，是否常覺得腦中思緒不停、難以停止？', '4-point frequency: 0 Never / 1 Occasionally / 2 Often / 3 Almost always', 'Past 2 weeks', 'M01, S01', 'INS-ONSET; COGNITIVE-AROUSAL', '思緒紛擾、神不守舍相關節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('M03', 'B', 'Core', 'Emotional symptom', 'Anxiety or tension', '焦慮或緊張', '主觀感到緊張、不安、難以放鬆或身心警覺。', '不是正式焦慮症診斷；若需篩檢可另接 GAD-9。', '最近兩週，您是否常感到焦慮、緊張或難以放鬆？', '4-point frequency: 0 Never / 1 Occasionally / 2 Often / 3 Almost always', 'Past 2 weeks', 'M01, M09, S01', 'INSOMNIA; STRESS; COMISA', '心神不寧、情志不舒相關節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('M04', 'B', 'Core', 'Emotional symptom', 'Irritability', '容易煩躁或易怒', '較平常更容易因小事感到煩躁、生氣或不耐煩。', '與 C02 怕熱或單純身體不適分開；聚焦情緒反應。', '最近兩週，您是否比平常更容易煩躁、易怒或不耐煩？', '4-point frequency: 0 Never / 1 Occasionally / 2 Often / 3 Almost always', 'Past 2 weeks', 'M09, S05, S14', 'DAYTIME; SLEEP-DEPRIVATION', '煩躁、情志不和相關節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('M05', 'B', 'Core', 'Emotional symptom', 'Depressed mood', '情緒低落', '持續或反覆感到低落、悲傷、缺乏愉悅。', '不是憂鬱症診斷；若需篩檢可另接PHQ-9。', '最近兩週，您是否常感到情緒低落、悲傷或提不起興趣？', '4-point frequency: 0 Never / 1 Occasionally / 2 Often / 3 Almost always', 'Past 2 weeks', 'S04, S06, S14', 'INSOMNIA; MOOD', '情志不暢、心神失養相關節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('M06', 'B', 'Extended', 'Arousal symptom', 'Easily startled', '容易受驚', '對聲音、動作或突發事件產生較強烈的驚嚇反應。', '與一般警覺性高或 M03 焦慮區分；可共存但概念不同。', '最近兩週，您是否比平常更容易被聲音或突發情況嚇到？', '4-point frequency: 0 Never / 1 Occasionally / 2 Often / 3 Almost always', 'Past 2 weeks', 'S08, M03', 'HYPERAROUSAL; STRESS', '易驚、膽怯、神不安相關節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('M07', 'B', 'Core', 'Cognitive symptom', 'Poor concentration', '注意力不集中', '難以持續專注、容易分心或完成需要注意力的工作較困難。', '與 M08 健忘區分；注意力是當下資訊處理，健忘是記憶保留或提取。', '最近兩週，您是否常難以集中注意力或容易分心？', '4-point frequency: 0 Never / 1 Occasionally / 2 Often / 3 Almost always', 'Past 2 weeks', 'M08, S12, S14', 'DAYTIME; COGNITION', '神疲、心神失養相關描述性節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('M08', 'B', 'Extended', 'Cognitive symptom', 'Forgetfulness', '健忘', '自覺比平常更容易忘記事情、約定或剛接收的資訊。', '與 M07 注意力不集中區分；必要時應另用認知量表評估。', '最近一個月，您是否覺得自己比平常更容易忘記事情？', '4-point frequency: 0 Never / 1 Occasionally / 2 Often / 3 Almost always', 'Past 1 month', 'M07, S05, S09', 'COGNITION; OSA; INSUFFICIENT-SLEEP', '健忘、心腎與腦髓相關知識節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('M09', 'B', 'Core', 'Contextual modifier', 'Stress-related worsening of sleep', '壓力使睡眠惡化', '壓力事件或心理負荷增加時，睡眠症狀明顯惡化。', '此項是觸發或調節因子，不是獨立精神症狀。', '當壓力增加時，您的入睡、夜醒或睡眠品質是否會明顯變差？', '4-point frequency: 0 Never / 1 Occasionally / 2 Often / 3 Almost always', 'Past 1 month', 'M01, M03, S01, S02', 'STRESS; INSOMNIA', '情志影響心神與睡眠之關聯節點');

-- ---------------- Module C ----------------
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('C01', 'C', 'Core', 'Thermal symptom', 'Cold intolerance', '怕冷', '在他人覺得舒適的環境中仍容易感到寒冷。', '與 C03 手腳冰冷區分；本項是全身主觀耐寒能力下降。', '最近兩週，您是否比周遭的人更容易覺得冷？', '4-point frequency: 0 Never / 1 Occasionally / 2 Often / 3 Almost always', 'Past 2 weeks', 'C03, B01', 'THERMOREGULATION', '畏寒、陽氣與衛外功能相關節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('C02', 'C', 'Core', 'Thermal symptom', 'Heat intolerance', '怕熱', '在他人覺得舒適的環境中仍容易覺得悶熱或難以耐受熱。', '與 C05 潮熱區分；怕熱通常較持續，潮熱為陣發性。', '最近兩週，您是否比周遭的人更容易覺得熱或難以耐受熱環境？', '4-point frequency: 0 Never / 1 Occasionally / 2 Often / 3 Almost always', 'Past 2 weeks', 'C05, C06', 'THERMOREGULATION; MENOPAUSE', '惡熱、內熱相關知識節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('C03', 'C', 'Core', 'Peripheral thermal symptom', 'Cold extremities', '手腳冰冷', '手掌、足部或四肢末端經常感到冰冷。', '可與 C01 共存，但本項聚焦末梢部位。', '最近兩週，您的手或腳是否經常感到冰冷？', '4-point frequency: 0 Never / 1 Occasionally / 2 Often / 3 Almost always', 'Past 2 weeks', 'C01, B11', 'THERMOREGULATION', '四肢厥冷、陽氣與氣血運行相關節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('C04', 'C', 'Extended', 'Peripheral thermal symptom', 'Heat in palms or soles', '手心或足心發熱', '手掌或足底反覆出現主觀熱感，未必伴全身發熱。', '與 C02 全身怕熱及 C05 潮熱區分。', '最近兩週，您是否常覺得手心或腳底發熱？', '4-point frequency: 0 Never / 1 Occasionally / 2 Often / 3 Almost always', 'Past 2 weeks', 'C02, C05, F01', 'THERMOREGULATION', '五心煩熱相關描述性節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('C05', 'C', 'Core', 'Vasomotor symptom', 'Hot flushes', '潮熱或熱潮紅', '突然出現由胸頸或全身向上擴散的熱感，可伴臉紅或出汗。', '與持續怕熱 C02 區分；本項為陣發性發作。', '最近兩週，您是否曾突然出現一陣熱感、臉紅或熱潮紅？', '4-point frequency: 0 Never / 1 Occasionally / 2 Often / 3 Almost always', 'Past 2 weeks', 'C02, C06, H01', 'MENOPAUSE; INS-MAINT', '潮熱、陰陽失調相關節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('C06', 'C', 'Core', 'Autonomic symptom', 'Night sweats', '夜間盜汗', '睡眠期間出汗，醒後才察覺，且非單純因室溫或棉被過厚。', '與 C07 自汗區分；需排除環境過熱及發燒。', '最近兩週，您是否曾在睡眠中出汗，醒來才發現衣服或床鋪潮濕？', '4-point frequency: 0 Never / 1 Occasionally / 2 Often / 3 Almost always', 'Past 2 weeks', 'C05, F01, S02', 'INS-MAINT; MENOPAUSE', '盜汗、陰液與衛氣相關節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('C07', 'C', 'Extended', 'Autonomic symptom', 'Spontaneous sweating', '自汗', '清醒且未明顯運動或處於高溫時，仍容易出汗。', '與 C06 夜間盜汗及正常運動出汗區分。', '最近兩週，您在白天沒有明顯運動或炎熱時，是否仍容易出汗？', '4-point frequency: 0 Never / 1 Occasionally / 2 Often / 3 Almost always', 'Past 2 weeks', 'B01, B08', 'AUTONOMIC', '自汗、衛氣不固相關節點');

-- ---------------- Module D ----------------
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('F01', 'D', 'Core', 'Oral symptom', 'Dry mouth', '口乾', '主觀感覺口腔內乾燥、唾液不足或黏膜不舒適。', '不一定會想喝水；與 F02 咽乾、F03 口渴分開。', '最近兩週，您是否常覺得嘴巴裡乾燥，即使不一定想喝水？', '4-point frequency: 0 Never / 1 Occasionally / 2 Often / 3 Almost always', 'Past 2 weeks', 'F02, F03, S09, C06', 'OSA; MOUTH-BREATHING; FLUID', '口乾、津液不足或燥象相關節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('F02', 'D', 'Core', 'Throat symptom', 'Dry throat', '咽乾', '主觀感覺咽喉部乾燥、乾澀或需要清喉嚨。', '部位在咽喉，不等同口腔乾燥或飲水欲望。', '最近兩週，您是否常覺得喉嚨乾燥或乾澀？', '4-point frequency: 0 Never / 1 Occasionally / 2 Often / 3 Almost always', 'Past 2 weeks', 'F01, F03, S09', 'OSA; MOUTH-BREATHING; AIRWAY', '咽乾、燥與津液相關節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('F03', 'D', 'Core', 'Fluid-regulation symptom', 'Increased thirst', '口渴', '主觀出現明顯飲水需求或想喝水的感覺。', '是行為驅動的飲水欲望；可無口乾，也可與 F01/F02 共存。', '最近兩週，您是否常明顯想喝水或覺得口渴？', '4-point frequency: 0 Never / 1 Occasionally / 2 Often / 3 Almost always', 'Past 2 weeks', 'F01, F02, F04, F05', 'FLUID; METABOLIC', '口渴、津液與寒熱偏好相關節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('F04', 'D', 'Extended', 'Preference', 'Preference for cold drinks', '偏好冷飲', '出現口渴或飲水時，明顯偏好冷水或冰飲。', '是偏好而非飲用量；與 F05 互斥或可設主要偏好。', '當您口渴時，是否通常偏好冷水或冰飲？', 'Single- or multiple-choice categorical response', 'Usual pattern in past 1 month', 'F03, C02', 'FLUID; HEAT-PREFERENCE', '喜冷飲、寒熱偏好節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('F05', 'D', 'Extended', 'Preference', 'Preference for warm drinks', '偏好溫熱飲', '出現口渴或飲水時，明顯偏好溫水或熱飲。', '是偏好而非飲用量；與 F04 分開。', '當您口渴時，是否通常偏好溫水或熱飲？', 'Single- or multiple-choice categorical response', 'Usual pattern in past 1 month', 'F03, C01', 'FLUID; COLD-PREFERENCE', '喜熱飲、寒熱偏好節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('F06', 'D', 'Extended', 'Taste symptom', 'Bitter taste', '口苦', '在未食用苦味食物時，仍反覆感到口中有苦味。', '需與藥物、食物殘留或口腔疾病造成的味覺改變區分。', '最近兩週，您是否常在沒有吃苦味食物時仍覺得口中發苦？', '4-point frequency: 0 Never / 1 Occasionally / 2 Often / 3 Almost always', 'Past 2 weeks', 'G05, M09', 'STRESS; DIGESTIVE', '口苦、少陽與肝膽相關知識節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('F07', 'D', 'Extended', 'Oral symptom', 'Sticky mouth', '口中黏膩', '口腔內感到黏、膩、清爽感不足，未必真的口乾。', '與 F01 乾燥感分開；可有唾液但質地黏稠。', '最近兩週，您是否常覺得口中黏膩、不清爽？', '4-point frequency: 0 Never / 1 Occasionally / 2 Often / 3 Almost always', 'Past 2 weeks', 'F08, G03', 'PHLEGM-DAMP; DIGESTIVE', '口黏、痰濕相關節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('F08', 'D', 'Extended', 'Respiratory secretion symptom', 'Excessive phlegm or sputum', '痰多', '自覺咽喉或呼吸道分泌物較多，需要咳出或頻繁清喉嚨。', '需與 F02 單純咽乾、鼻涕倒流或急性感染區分。', '最近兩週，您是否常覺得痰多、需要咳痰或頻繁清喉嚨？', '4-point frequency: 0 Never / 1 Occasionally / 2 Often / 3 Almost always', 'Past 2 weeks', 'F07, S09, G05', 'OSA; AIRWAY; PHLEGM', '痰多、痰濕與肺脾相關節點');

-- ---------------- Module E ----------------
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('G01', 'E', 'Core', 'Appetite symptom', 'Poor appetite', '食慾不佳', '進食欲望下降，較平常不想吃東西。', '與 G04 吃後不適或「刻意節食」區分。', '最近兩週，您是否常覺得沒有食慾或不太想吃東西？', '4-point frequency: 0 Never / 1 Occasionally / 2 Often / 3 Almost always', 'Past 2 weeks', 'B01, G03, G04', 'DIGESTIVE; GENERAL', '食少、脾胃運化相關節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('G02', 'E', 'Extended', 'Appetite symptom', 'Increased appetite', '食慾增加', '進食欲望或食量較平常明顯增加。', '需與 L09 夜間進食及因運動增加食量區分。', '最近兩週，您的食慾或食量是否比平常明顯增加？', 'Decrease / No change / Increase + optional amount', 'Past 2 weeks', 'L09, B12', 'METABOLIC; SLEEP-DEPRIVATION', '多食易飢、胃熱等知識節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('G03', 'E', 'Core', 'Gastrointestinal symptom', 'Abdominal bloating', '腹脹', '腹部主觀脹滿、緊繃或氣體感，可在進食後加重。', '與單純肥胖或腹圍增加區分。', '最近兩週，您是否常覺得腹部脹滿或有很多氣？', '4-point frequency: 0 Never / 1 Occasionally / 2 Often / 3 Almost always', 'Past 2 weeks', 'G04, F07', 'DIGESTIVE; SLEEP-DISRUPTION', '腹脹、脾胃與氣機相關節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('G04', 'E', 'Core', 'Upper-GI symptom', 'Dyspepsia or epigastric fullness', '消化不良或胃脘脹悶', '上腹部飽脹、消化慢、餐後不適或胃脘悶脹。', '與 G03 全腹脹及 G05 胃灼熱/酸水區分。', '最近兩週，您是否常覺得上腹部脹悶、消化慢或吃後不舒服？', '4-point frequency: 0 Never / 1 Occasionally / 2 Often / 3 Almost always', 'Past 2 weeks', 'G03, G05, L09', 'DIGESTIVE; INS-MAINT', '胃脘痞滿、脾胃不和相關節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('G05', 'E', 'Core', 'Reflux symptom', 'Heartburn or acid regurgitation', '胃灼熱或酸水逆流', '胸骨後灼熱感、酸液或食物逆流至喉嚨或口腔。', '與 B07 胸悶及 F06 口苦區分；夜間症狀需記錄時間。', '最近兩週，您是否常有胃灼熱、火燒心或酸水跑到喉嚨？', '4-point frequency: 0 Never / 1 Occasionally / 2 Often / 3 Almost always', 'Past 2 weeks', 'F06, F08, B07, L09', 'INS-MAINT; OSA; REFLUX', '胃氣上逆相關節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('G06', 'E', 'Extended', 'Gastrointestinal symptom', 'Nausea', '噁心', '有想吐、胃部翻攪或明顯不適的感覺。', '與暈眩引起不適及實際嘔吐分開。', '最近兩週，您是否常覺得噁心或想吐？', '4-point frequency: 0 Never / 1 Occasionally / 2 Often / 3 Almost always', 'Past 2 weeks', 'G04, B06', 'DIGESTIVE', '噁心、胃氣上逆相關節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('G07', 'E', 'Core', 'Bowel symptom', 'Loose stools', '大便偏軟或不成形', '排便質地較軟、糊狀或不成形，但不一定增加排便次數。', '與 G08 腹瀉區分；腹瀉通常同時有次數增加或急迫性。', '最近兩週，您的大便是否常偏軟、糊狀或不成形？', '4-point frequency: 0 Never / 1 Occasionally / 2 Often / 3 Almost always', 'Past 2 weeks', 'G08, B01', 'DIGESTIVE', '便溏、脾胃運化相關節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('G08', 'E', 'Core', 'Bowel symptom', 'Diarrhea', '腹瀉', '排便次數增加且大便稀水，常伴急迫感或不適。', '不等同單純便軟 G07；必要時記錄每日次數與持續時間。', '最近兩週，您是否曾出現排便次數增加且大便稀水的情形？', '4-point frequency: 0 Never / 1 Occasionally / 2 Often / 3 Almost always; optional stools/day', 'Past 2 weeks', 'G07, K03', 'DIGESTIVE; SLEEP-DISRUPTION', '泄瀉、脾胃與濕相關節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('G09', 'E', 'Core', 'Bowel symptom', 'Constipation', '便秘', '排便困難、次數減少、糞便硬或需要明顯用力。', '可由多個面向構成；若需要研究精確度，可另記頻率與 Bristol stool form。', '最近兩週，您是否常排便困難、次數太少或需要很用力？', '4-point frequency: 0 Never / 1 Occasionally / 2 Often / 3 Almost always; optional bowel movements/week', 'Past 2 weeks', 'G10, F03', 'DIGESTIVE; SLEEP', '便秘、津虧與氣機相關節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('G10', 'E', 'Extended', 'Bowel symptom', 'Sensation of incomplete evacuation', '排便不盡感', '排便後仍覺得沒有排乾淨或很快又想排便。', '與排便次數及糞便硬度分開。', '最近兩週，您排便後是否常覺得沒有排乾淨？', '4-point frequency: 0 Never / 1 Occasionally / 2 Often / 3 Almost always', 'Past 2 weeks', 'G09, K03', 'DIGESTIVE', '後重、氣機不暢相關節點');

-- ---------------- Module F ----------------
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('K01', 'F', 'Core', 'Urinary symptom', 'Nocturia', '夜尿', '主要睡眠時段中因需要排尿而醒來，並實際起床排尿。', '與 K02 白天尿頻分開；需記錄每晚次數，且要先睡著後再醒來排尿。', '最近兩週，您平均每晚會因想尿尿而起床幾次？', 'Numeric count + optional frequency rating', 'Past 2 weeks', 'S02, K02, L10', 'INS-MAINT; OSA; LUTS', '夜尿、腎與膀胱氣化相關節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('K02', 'F', 'Extended', 'Urinary symptom', 'Urinary frequency', '尿頻', '清醒期間排尿次數明顯較多，或間隔較短。', '與 K01 夜尿及單純大量飲水造成的排尿增加區分。', '最近兩週，您白天是否常需要頻繁排尿？', '4-point frequency: 0 Never / 1 Occasionally / 2 Often / 3 Almost always; optional voids/day', 'Past 2 weeks', 'K01, K03, F03', 'LUTS; FLUID', '尿頻、腎與膀胱氣化相關節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('K03', 'F', 'Extended', 'Urinary symptom', 'Urinary urgency', '尿急', '突然且難以延後的強烈排尿感。', '與一般「膀胱已滿」或單純頻尿分開。', '最近兩週，您是否常突然很急著要尿，難以忍住？', '4-point frequency: 0 Never / 1 Occasionally / 2 Often / 3 Almost always', 'Past 2 weeks', 'K02, G08', 'LUTS; SLEEP-DISRUPTION', '尿急、膀胱氣化相關節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('K04', 'F', 'Core', 'Musculoskeletal/TCM kidney-related', 'Low back soreness or weakness', '腰部痠軟', '腰部持續或反覆痠、沉、無力感，不以尖銳疼痛為主。', '與急性腰痛、放射痛或 B03 全身肌肉痠痛區分。', '最近兩週，您是否常覺得腰部痠、軟或沒有力？', '4-point frequency: 0 Never / 1 Occasionally / 2 Often / 3 Almost always', 'Past 2 weeks', 'B01, B03', 'GENERAL; TCM-KIDNEY', '腰痠、腎系相關知識節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('K05', 'F', 'Extended', 'Sensory symptom', 'Tinnitus', '耳鳴', '在沒有外部聲音時，耳內或頭部感到鳴響、嗡聲或其他聲音。', '與聽力下降分開；需記錄單側/雙側及是否影響睡眠。', '最近一個月，您是否常有耳鳴，且可能影響入睡或夜間睡眠？', '4-point frequency: 0 Never / 1 Occasionally / 2 Often / 3 Almost always', 'Past 1 month', 'S01, S02', 'INSOMNIA; SENSORY', '耳鳴、腎開竅於耳相關節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('K06', 'F', 'Conditional', 'Sensitive symptom', 'Change in sexual function', '性功能變化', '性慾、勃起、潤滑或其他性功能較個人平常狀態明顯改變。', '敏感且非第一版核心題；須可選擇不回答，且不得直接推論證型。', '最近三個月，您的性慾或性功能是否較平常明顯改變？', 'Decrease / No change / Increase + optional amount; option: prefer not to answer', 'Past 3 months', 'M03, M05, H01', 'GENERAL; MEDICATION; HORMONAL', '腎系與生殖相關知識節點');

-- ---------------- Module G ----------------
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('B01', 'G', 'Core', 'General somatic symptom', 'General weakness', '全身無力或容易乏力', '不限定於白天或睡醒後的全身體力不足、做事容易沒力。', '與 S14 日間疲倦、S12 嗜睡及 K04 腰痠軟分開。', '最近兩週，您是否常覺得全身沒力或做事容易乏力？', '4-point frequency: 0 Never / 1 Occasionally / 2 Often / 3 Almost always', 'Past 2 weeks', 'S14, S06, K04', 'DAYTIME; GENERAL', '乏力、氣虛相關描述性節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('B02', 'G', 'Extended', 'General somatic symptom', 'Heavy limbs', '四肢沉重', '手腳或四肢有沉、重、抬動不輕快的感覺。', '與 B01 無力及 B03 痠痛區分。', '最近兩週，您是否常覺得手腳或四肢沉重、不輕快？', '4-point frequency: 0 Never / 1 Occasionally / 2 Often / 3 Almost always', 'Past 2 weeks', 'B01, F07', 'GENERAL; PHLEGM-DAMP', '肢體困重、濕相關節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('B03', 'G', 'Extended', 'Musculoskeletal symptom', 'Muscle soreness', '肌肉痠痛', '肌肉持續或反覆痠、緊、痛，可能影響休息或睡眠。', '與 K04 腰痠軟及 B04 肩頸僵硬區分。', '最近兩週，您是否常有肌肉痠痛，並影響休息或睡眠？', '4-point frequency: 0 Never / 1 Occasionally / 2 Often / 3 Almost always', 'Past 2 weeks', 'B04, K04, S02', 'INS-MAINT; PAIN', '痠痛、氣血運行相關節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('B04', 'G', 'Extended', 'Musculoskeletal symptom', 'Neck or shoulder stiffness', '肩頸僵硬', '肩部或頸部有緊繃、僵硬或活動不舒適。', '與頭痛 B05 或全身肌肉痠痛 B03 分開。', '最近兩週，您是否常覺得肩頸緊繃或僵硬？', '4-point frequency: 0 Never / 1 Occasionally / 2 Often / 3 Almost always', 'Past 2 weeks', 'B03, B05', 'INSOMNIA; PAIN', '經筋、氣血運行相關節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('B05', 'G', 'Core', 'Neurologic/somatic symptom', 'Headache', '頭痛', '頭部任何部位出現疼痛、脹痛或壓迫感。', '需另記晨起、夜間、偏側及危險警訊；不能自動歸因於睡眠。', '最近兩週，您是否常有頭痛？若有，是否多在早晨醒來時出現？', '4-point frequency: 0 Never / 1 Occasionally / 2 Often / 3 Almost always; optional timing', 'Past 2 weeks', 'S09, S10, B04', 'OSA; INSOMNIA; PAIN', '頭痛、經絡與氣血相關節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('B06', 'G', 'Core', 'Neurologic/somatic symptom', 'Dizziness or vertigo', '頭暈或眩暈', '感到頭昏、飄浮、不穩，或周遭/自身旋轉。', '可在後續拆成 lightheadedness 與 vertigo；v2.1 暫合併為入口節點。', '最近兩週，您是否常感到頭暈、站立不穩或天旋地轉？', '4-point frequency: 0 Never / 1 Occasionally / 2 Often / 3 Almost always', 'Past 2 weeks', 'B01, G06', 'GENERAL; SAFETY', '眩暈、風痰氣血相關節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('B07', 'G', 'Core', 'Cardiorespiratory symptom', 'Chest oppression', '胸悶', '胸前有壓迫、悶塞或不舒適感，但不一定疼痛。', '與 G05 胃灼熱、B08 呼吸不順及急性胸痛區分；危險症狀需即時就醫。', '最近兩週，您是否常覺得胸口悶、壓迫或不舒適？', '4-point frequency: 0 Never / 1 Occasionally / 2 Often / 3 Almost always', 'Past 2 weeks', 'B08, B09, G05', 'OSA; ANXIETY; SAFETY', '胸悶、氣機不暢與痰阻相關節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('B08', 'G', 'Core', 'Cardiorespiratory symptom', 'Shortness of breath', '呼吸不順或喘', '主觀感到呼吸費力、氣不夠用或容易喘。', '與 S11 夜間喘醒分開；若急性、胸痛或低血氧需醫療處置。', '最近兩週，您是否常覺得呼吸不順、氣不夠用或容易喘？', '4-point frequency: 0 Never / 1 Occasionally / 2 Often / 3 Almost always', 'Past 2 weeks', 'S11, B07, B09', 'OSA; CARDIOPULMONARY; SAFETY', '短氣、少氣、肺氣相關節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('B09', 'G', 'Core', 'Autonomic/cardiac symptom', 'Palpitations', '心悸', '自覺心跳快速、強烈、不規則或心臟跳動感明顯。', '與 M03 焦慮分開；可由焦慮、心律、藥物或其他因素造成。', '最近兩週，您是否常覺得心跳很快、很重或不規則？', '4-point frequency: 0 Never / 1 Occasionally / 2 Often / 3 Almost always', 'Past 2 weeks', 'M03, B07, S01', 'INSOMNIA; ANXIETY; CARDIAC', '心悸、心神與氣血相關節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('B10', 'G', 'Extended', 'Fluid-retention symptom', 'Edema', '水腫', '眼皮、手、腳踝或小腿出現腫脹、按壓凹陷或戒指鞋襪變緊。', '與單純體重增加或久坐後短暫腫脹區分。', '最近兩週，您是否常有眼皮、手、腳踝或小腿水腫？', '4-point frequency: 0 Never / 1 Occasionally / 2 Often / 3 Almost always', 'Past 2 weeks', 'B12, C03', 'OSA; CARDIOMETABOLIC; FLUID', '水腫、水濕與脾腎相關節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('B11', 'G', 'Core', 'Sensorimotor sleep symptom', 'Restless legs symptoms', '不寧腿樣症狀', '休息或躺下時腿部不舒服並有強烈移動衝動，活動後暫時改善。', '不是一般腿痠或抽筋；需同時具備休息時加重、活動改善等特徵。', '晚上坐著或躺下時，您的腿是否常不舒服、很想動，動一動會比較好？', '4-point frequency: 0 Never / 1 Occasionally / 2 Often / 3 Almost always', 'Past 1 month', 'S01, S02, B03', 'RLS; INS-ONSET; INS-MAINT', '腿部躁動可作描述性節點，不直接套用證型');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('B12', 'G', 'Core', 'Anthropometric change', 'Weight change', '近期體重變化', '在非刻意減重或增重下，體重較近期基準明顯改變。', '需記錄方向、幅度與期間；不等同 BMI。', '最近三個月，您的體重是否在非刻意情況下明顯增加或減少？', 'Decrease / No change / Increase + optional amount; optional kilograms', 'Past 3 months', 'G02, B10, S09', 'OSA; METABOLIC; GENERAL', '形體消長與脾腎代謝相關節點');

-- ---------------- Module H ----------------
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('W01', 'H', 'Conditional', 'Reproductive status', 'Menstrual and reproductive status', '月經與生殖階段', '目前所處的月經、生殖或更年期階段。', '屬背景狀態，不是症狀；應採條件式顯示。', '請選擇目前最符合您的狀態：有月經／停經過渡期／停經後／懷孕／產後／其他。', 'Single- or multiple-choice categorical response', 'Current status', 'C05, C06, W07', 'MENOPAUSE; PREGNANCY; CONTEXT', '女子胞、沖任與生命階段相關知識節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('W02', 'H', 'Conditional', 'Menstrual symptom', 'Irregular menstrual cycles', '月經週期不規則', '月經週期長短明顯變動、跳月或難以預測。', '需與已停經、懷孕、荷爾蒙治療造成的變化區分。', '過去六個月，您的月經週期是否常不規則或難以預測？', '4-point frequency: 0 Never / 1 Occasionally / 2 Often / 3 Almost always', 'Past 6 months', 'W01, W06', 'HORMONAL; SLEEP', '月經不調、沖任相關節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('W03', 'H', 'Conditional', 'Menstrual symptom', 'Heavy menstrual bleeding', '經血量過多', '經血量明顯多於個人平常，需頻繁更換衛生用品或有大量血塊。', '與 W04 經量過少分開；異常大量出血需臨床評估。', '過去六個月，您的經血量是否明顯過多或常有大量血塊？', '4-point frequency: 0 Never / 1 Occasionally / 2 Often / 3 Almost always', 'Past 6 months', 'W01, B01', 'HORMONAL; ANEMIA-RISK', '月經過多、沖任與氣血相關節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('W04', 'H', 'Conditional', 'Menstrual symptom', 'Scanty menstrual bleeding', '經血量過少', '經血量較個人平常明顯減少或經期很短。', '與 W03 分開；需考慮年齡、懷孕、體重與藥物情境。', '過去六個月，您的經血量是否明顯偏少或經期很短？', '4-point frequency: 0 Never / 1 Occasionally / 2 Often / 3 Almost always', 'Past 6 months', 'W01, B12', 'HORMONAL', '月經過少、沖任與氣血相關節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('W05', 'H', 'Conditional', 'Menstrual symptom', 'Dysmenorrhea', '經痛', '月經前後或行經期間出現下腹或腰部疼痛，影響活動或睡眠。', '與一般腹痛及 K04 腰痠分開；需記錄是否影響睡眠。', '月經來時，您是否常有下腹或腰部疼痛，並影響活動或睡眠？', '4-point severity: 0 None / 1 Mild / 2 Moderate / 3 Severe', 'Past 6 months', 'K04, S02', 'PAIN; INS-MAINT', '痛經、沖任與氣血相關節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('W06', 'H', 'Conditional', 'Premenstrual symptom', 'Premenstrual symptoms', '經前症狀', '月經前反覆出現情緒、乳房脹痛、腹脹、頭痛或其他不適，月經後改善。', '需有週期性；與持續性情緒或身體症狀分開。', '月經前一至兩週，您是否常出現情緒或身體不適，月經來後改善？', '4-point frequency: 0 Never / 1 Occasionally / 2 Often / 3 Almost always', 'Past 6 months', 'M04, G03, B05, W07', 'PMS; INSOMNIA', '經前諸證、沖任與肝脾相關節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('W07', 'H', 'Conditional', 'Contextual modifier', 'Cycle-related worsening of sleep', '月經週期相關睡眠惡化', '睡眠症狀在經前、行經或其他固定週期階段規律惡化。', '是時間關係與調節因子，不等同單一睡眠症狀。', '您的入睡、夜醒或睡眠品質，是否會在經前或月經期間明顯變差？', '4-point frequency: 0 Never / 1 Occasionally / 2 Often / 3 Almost always', 'Past 6 months', 'W05, W06, S01, S02', 'MENSTRUAL; INSOMNIA', '月經週期與寤寐變化相關節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('W08', 'H', 'Conditional', 'Contextual modifier', 'Pregnancy or postpartum-related sleep change', '懷孕或產後相關睡眠變化', '懷孕或產後階段新出現或明顯加重的睡眠問題。', '只在 W01 選擇懷孕或產後時顯示；需考慮育兒照護造成的外在干擾。', '自懷孕或生產後，您的睡眠是否新出現或明顯變差？', 'Decrease / No change / Increase + optional amount', 'Current pregnancy or postpartum period', 'W01, S02, K01, L12', 'PREGNANCY; POSTPARTUM; INSOMNIA', '妊娠產後與寤寐變化相關節點');

-- ---------------- Module I ----------------
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('L01', 'I', 'Core', 'Substance use', 'Tobacco or nicotine use', '菸品或尼古丁使用', '使用紙菸、電子煙、加熱菸、尼古丁袋或其他尼古丁產品。', '需記錄種類、頻率與睡前使用；過去使用者與目前使用者分開。', '目前是否使用任何菸品或尼古丁產品？若有，多久一次？', 'Frequency and quantity', 'Current and past 1 month', 'S01, S02, S09', 'INSOMNIA; OSA; SUBSTANCE', '刺激物與肺系相關背景節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('L02', 'I', 'Core', 'Substance use', 'Alcohol use', '飲酒', '攝取含酒精飲品，包括作為助眠用途。', '需記錄頻率、標準杯數及睡前時點；不將飲酒等同酒精使用疾患。', '過去一個月，您多久喝一次酒？通常喝多少？是否曾為了助眠而喝？', 'Frequency and quantity', 'Past 1 month', 'S02, S09, S10', 'INS-MAINT; OSA; SUBSTANCE', '酒性與濕熱相關背景節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('L03', 'I', 'Core', 'Substance use', 'Caffeine intake', '咖啡因攝取', '攝取咖啡、茶、能量飲料、可樂或含咖啡因藥品。', '應記錄每日量及最後攝取時間；茶可在此統一記錄，避免重複節點。', '過去兩週，您每天大約攝取多少含咖啡因飲品？最後一杯通常在幾點？', 'Frequency and quantity + last intake time', 'Past 2 weeks', 'S01, M02', 'INS-ONSET; SUBSTANCE', '刺激性飲食與寤寐背景節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('L04', 'I', 'Core', 'Health behavior', 'Regular exercise', '規律運動', '具有一定頻率、時間與強度的身體活動或運動。', '需區分日常走動與有計畫運動；可另接 IPAQ 或穿戴裝置資料。', '過去一個月，您每週有幾天進行至少 30 分鐘的中等強度以上運動？', 'Days/week + minutes/session', 'Past 1 month', 'S05, S06, B12', 'SLEEP-QUALITY; CIRCADIAN; METABOLIC', '動則生陽、氣血運行之背景節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('L05', 'I', 'Core', 'Sleep behavior', 'Screen use before bed', '睡前使用螢幕設備', '睡前使用手機、平板、電腦或電視，可能延後就寢或增加認知刺激。', '需記錄距離關燈時間與使用目的；不等同 L08 作息不規律。', '過去兩週，您通常在睡前多久仍使用手機、平板、電腦或電視？', 'Minutes before intended sleep + frequency', 'Past 2 weeks', 'S01, M02, L08', 'INS-ONSET; CIRCADIAN; BEHAVIOR', '夜間刺激與寤寐背景節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('L06', 'I', 'Core', 'Sleep behavior', 'Daytime napping', '午睡或白天小睡', '主要夜間睡眠之外的計畫性或習慣性睡眠。', '與 S13 非預期打瞌睡區分；需記錄時間、長度與是否太晚。', '過去兩週，您平均每週午睡幾天？每次大約多久？', 'Days/week + minutes + timing', 'Past 2 weeks', 'S01, S13, K01', 'INS-ONSET; DAYTIME; BEHAVIOR', '晝寐與寤寐節律背景節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('L07', 'I', 'Core', 'Occupational factor', 'Shift work', '輪班工作', '工作時段包含夜班、晚班、早班輪替或不固定班別。', '需區分固定夜班與輪替班；本項是外在暴露，不是睡眠症狀。', '目前是否有夜班、晚班或輪替班工作？', 'Single- or multiple-choice categorical response', 'Current status and past 3 months', 'L08, S05, S14', 'CIRCADIAN; SHIFT-WORK', '晝夜顛倒與寤寐失常背景節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('L08', 'I', 'Core', 'Sleep schedule behavior', 'Variable sleep schedule', '睡眠時間不規律', '平日或不同日之上床、入睡或起床時間差異明顯。', '與 L07 輪班分開；即使沒有輪班，也可因生活習慣造成。', '過去兩週，您每天的上床與起床時間是否常相差兩小時以上？', '4-point frequency: 0 Never / 1 Occasionally / 2 Often / 3 Almost always; optional social jetlag hours', 'Past 2 weeks', 'L07, L05, S05', 'CIRCADIAN; INSOMNIA', '寤寐節律失常背景節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('L09', 'I', 'Extended', 'Eating behavior', 'Late-night eating', '睡前或夜間進食', '接近睡眠時間或夜間醒來後進食正餐、點心或高熱量食物。', '飲水不算；需記錄距離睡眠時間與食物量。', '過去兩週，您是否常在睡前兩小時內或半夜醒來後進食？', '4-point frequency: 0 Never / 1 Occasionally / 2 Often / 3 Almost always', 'Past 2 weeks', 'G02, G04, G05', 'INS-MAINT; REFLUX; METABOLIC', '夜食、脾胃不和相關背景節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('L10', 'I', 'Core', 'Medication exposure', 'Sleep medication use', '助眠藥物使用', '使用處方或非處方藥物以幫助入睡、維持睡眠或鎮靜。', '需記錄名稱、劑量、頻率與醫囑；不判定適當性。', '過去一個月，您是否使用任何助眠、鎮靜或抗焦慮藥物？', 'Frequency and quantity + medication name', 'Past 1 month', 'S01, S02, S12', 'MEDICATION; INSOMNIA; SAFETY', '藥物介入背景節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('L11', 'I', 'Extended', 'Complementary exposure', 'Herbal medicine or supplement use', '中藥或保健品使用', '使用中藥方、單味藥、褪黑激素或其他保健品以改善睡眠或身體狀況。', '需記錄產品或處方名稱；不得把使用行為當成療效證據。', '過去一個月，您是否使用中藥、褪黑激素或其他保健品來幫助睡眠？', 'Frequency and quantity + product name', 'Past 1 month', 'L10, S01', 'COMPLEMENTARY; MEDICATION', '中藥與保健品暴露背景節點');
INSERT INTO stfd_features (feature_id, module_code, priority, feature_type, name_en, name_zh_tw, clinical_definition, clinical_boundary, patient_question_zh_tw, response_type, time_window, related_features, sleep_relevance, tcm_knowledge_link) VALUES ('L12', 'I', 'Core', 'Environmental factor', 'Sleep environment disturbance', '睡眠環境干擾', '噪音、光線、溫度、床伴、照護責任或其他外在因素持續干擾睡眠。', '本項聚焦外在環境，而非內在睡眠障礙。', '過去兩週，噪音、光線、溫度、床伴或照護工作是否常干擾您的睡眠？', '4-point frequency: 0 Never / 1 Occasionally / 2 Often / 3 Almost always + multiple-choice source', 'Past 2 weeks', 'S02, C01, C02, W08', 'ENVIRONMENT; INS-MAINT', '居處與外在擾動背景節點');

-- 欄位說明
COMMENT ON COLUMN stfd_features.feature_id IS '如 S01、M01、F01';
COMMENT ON COLUMN stfd_features.module_code IS 'A-I';
COMMENT ON COLUMN stfd_features.priority IS 'Core/Extended/Conditional';
COMMENT ON COLUMN stfd_features.feature_type IS '如 Sleep symptom';
COMMENT ON COLUMN stfd_features.name_en IS '英文概念名稱';
COMMENT ON COLUMN stfd_features.name_zh_tw IS '中文概念名稱';
COMMENT ON COLUMN stfd_features.clinical_definition IS '臨床定義';
COMMENT ON COLUMN stfd_features.clinical_boundary IS '邊界／與相近概念的區分';
COMMENT ON COLUMN stfd_features.patient_question_zh_tw IS '病人友善問句';
COMMENT ON COLUMN stfd_features.response_type IS '建議回答格式';
COMMENT ON COLUMN stfd_features.time_window IS '回顧時間窗';
COMMENT ON COLUMN stfd_features.related_features IS '關聯Feature ID清單';
COMMENT ON COLUMN stfd_features.sleep_relevance IS '睡眠相關標籤';
COMMENT ON COLUMN stfd_features.tcm_knowledge_link IS '中醫知識節點描述';
